version: "3"

services:
    app:
        build:
          context: app
          dockerfile: docker/Dockerfile
        volumes: 
            - ./app:/home/user/Documents/poseEstimationMusic/app
        restart: always
